### ISSUE TITLE
Handles can't contain an underscore

### ISSUE THREAD

**Issue by justincy** [treehub-eng/firebase-rules#7]
Is there a particular reason for this decision?

**Comment by jonnymbgood** [comment]
It stems from deciding what constitutes a unique handle. Since `name`, `Name`, `NaMe`, etc should be considered the same handle, it would follow that `my name`, `my_name`, and `my-name` should also be the same handle. And since spaces are evil in urls, we should standardize on something. So I chose `-` like github did.

**Comment by jonnymbgood** [comment]
@justincy Are you ok with closing this issue?

**Comment by justincy** [comment]
Yeah
